[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NETLIFY_USE_PNPM = "true"
  NUXT_SANITY_PROJECT_ID = "lan2o0bx"
NUXT_SANITY_DATASET = "production"
NUXT_SANITY_API_READ_TOKEN = "sk8uJK1ps1ZrRf93YpGW4f3GZtrZ96elMKqWCs4SmDsDhCOT4z9Wx9tMaqHNyyBE6r0YDTQgmGC5gWWVi1Uex7s0wkQzwaUSnMxixUtfaRK5stTR3skYYLqZuxMIbTxsaZ8jhInamCkB5fm9i6KpXwQfyUPG96RenNtxQhSuJ1jYmfRpN8Fo"
NUXT_SANITY_STUDIO_URL = "https://layne-harris.sanity.studio/"

[[plugins]]
  package = "@netlify/plugin-nextjs"
